### ISSUE TITLE
Uncaught TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by pascalpp** [klorenz/atom-open-plus#12]
```
    GroupSortView       = require('./group_sort_view'),
```

I clicked in that path and triggered open-plus. That file (group_sort_view.js) doesn't exist.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [open-plus](https://github.com/klorenz/atom-open-plus) package, v0.6.0
### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:400

TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:400:13)
  at Object.posix.relative (path.js:467:14)
  at Object.module.exports.createFile (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:97:28)
  at Object.module.exports.fileCheckAndOpen (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:169:10)
  at Object.module.exports.fileCheckAndOpen (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
  at Object.module.exports.fileCheckAndOpen (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
  at Object.module.exports.fileCheckAndOpen (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
  at Object.module.exports.fileCheckAndOpen (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
  at Object.module.exports.fileCheckAndOpen (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
  at Object.module.exports.fileCheckAndOpen (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
  at Object.module.exports.fileCheckAndOpen (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
  at Object.module.exports.openFile (/Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:71:6)
  at /Users/pascal/.atom/packages/open-plus/lib/open-plus.coffee:228:23

```
### Commands

```
     -0:25.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:25.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:25.2.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
  7x -0:25 editor:move-to-next-word-boundary (atom-text-editor.editor.is-focused)
  2x -0:23.6.0 editor:move-to-previous-word-boundary (atom-text-editor.editor.is-focused)
  2x -0:22.8.0 subword-navigation:move-right (atom-text-editor.editor.is-focused)
     -0:21.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:20.8.0 subword-navigation:delete-left (atom-text-editor.editor.is-focused)
     -0:19.5.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:18 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:17.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.4.0 open-plus:open (atom-text-editor.editor.is-focused)
     -0:08.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.9.0 open-plus:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "atom-ternjs"
    ],
    "projectHome": "/Users/pascal/Projects",
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
atom-html-preview, v0.1.9
autocomplete-paths, v1.0.2
color-picker, v2.0.9
less-than-slash, v0.6.0
line-ending-converter, v1.2.0
linter, v1.1.0
linter-jshint, v0.1.7
markdown-scroll-sync, v0.4.0
oneliner, v0.1.4
open-plus, v0.6.0
pane-split-moves-tab, v0.0.1
project-manager, v1.15.11
run-in-browser, v0.1.3
subword-navigation, v2.9.0
tab-control, v0.6.7
the-closer, v0.5.0
trailing-semicolon, v1.1.0

# Dev
No dev packages
```

**Comment by ChuckPierce** [comment]
@pascalpp does this still not work for you?  It seems to be working on mine

**Comment by pascalpp** [comment]
still doesn't work. i have these settings for the open-plus package:
![image](https://cloud.githubusercontent.com/assets/1355312/12970984/56937b2a-d063-11e5-8be1-cf469b826223.png)

as i recall, it's supposed to open a new file by that name, using the same extension as the current file. is that correct?

when i invoke it, i just get:
![image](https://cloud.githubusercontent.com/assets/1355312/12971000/94a86d08-d063-11e5-88b5-e211dcbb7a6c.png)

that also happens if i add the extension to the filename.

**Comment by ChuckPierce** [comment]
yea it opens a new file for me...are you writing your own path to that file?

for example if I write

`index.js` and invoke it opens a file and when I save it it will save within the directory I'm in

if I write something like `app/index.js` and the `app` directory doesn't exist that error will come up.  A directory structure that doesn't exist will always bring up and error.  This can be implemented later but right now the program doesn't do that.

Maybe I'm missing something?

It also seems like assuming that the file you want to create should have the same file extension name as the current file is not a correct assumption.  It happens a lot for me that I'm including files with lots of different extensions.

**Comment by pascalpp** [comment]
From the readme:

> If word under cursor has no extension, and resolved file does not exist, extension from current file is added to filename.

**Comment by pascalpp** [comment]
FWIW, I'm not hurting for this feature; I just select the file in tree view and press D to duplicate it and create the new file I need.

**Comment by ChuckPierce** [comment]
okay so I have a [PR](https://github.com/klorenz/atom-open-plus/pull/18) that should fix this issue.  

If no file extension is given for the new file then it will use the extension of the current file.  That is still implemented.

My fix will cause it to not break if you have a `.something` on it.  Before if there was a filename like this `something.babel` it would error thinking .babel was an extension.  My PR makes sure that it looks and reads files in directories to make sure that file doesn't exist before creating it.

Hopefully this makes sense?  I've replicated what you've done here with the `./group_view` and it works on my end.

**Comment by pascalpp** [comment]
Nice!

**Comment by klorenz** [comment]
This is fixed now
