### ISSUE TITLE
add AMD path setting for requirejs path resolution

### ISSUE THREAD

**Issue by pascalpp** [klorenz/atom-open-plus#7]
for example:

```
    var User = require('model/user'),
        Group = require('model/group'); 
```

when I activate open-plus in one of those paths, it's unable to find the file because the path is relative to my AMD root directory, not relative to the current file. would love to be able to configure this in open-plus so it can attempt to resolve these paths correctly.

**Comment by klorenz** [comment]
Hi Pascal,

you mean you want to have a general configuration, if open-plus opens always with project directory as root?

**Comment by pascalpp** [comment]
Yeah basically a way to specific the root directory for resolving non-relative paths like the above.

**Comment by ChuckPierce** [comment]
yea this is the reason why I use this tool is to open my files based on the relative path of my application.  Sublimes Open-Include is able to do this well and can probably be implemented in a similar way
